#!/bin/bash

/bin/echo -e "[mesa-git]" >> /etc/pacman.conf
/bin/echo -e "Server = https://pkgbuild.com/~lcarlier/\$repo/\$arch" >> /etc/pacman.conf

/bin/echo -e "\n" >> /etc/pacman.conf
/bin/echo -e "[liquorix]" >> /etc/pacman.conf
/bin/echo -e "Server = https://liquorix.net/archlinux/\$repo/\$arch" >> /etc/pacman.conf

cat /etc/pacman.conf

pacman -Syu
pacman -S archlinux-keyring

/bin/echo -e "\e[1;32mPenambahan Mirrorlist Berhasil 5..4..3..2..1..\e[0m"
sleep 5
