#!/bin/bash

ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
hwclock --systohc
nano /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf
echo "KEYMAP=us" >> /etc/vconsole.conf
echo "anarki" >> /etc/hostname
echo "127.0.0.1 localhost" >> /etc/hosts
echo "::1       localhost" >> /etc/hosts
echo "127.0.1.1 anarki.localdomain anarki" >> /etc/hosts

#printf "\e[1;32mMasukan Kata Sandi ROOT\e[0m\n"
/bin/echo -e "\e[1;32mMasukan Kata Sandi ROOT Dalam 5..4..3..2..1..\e[0m"
sleep 5

passwd
