#!/bin/bash

/bin/echo -e "[mesa-git]" >> /etc/pacman.conf
/bin/echo -e "Server = https://pkgbuild.com/~lcarlier/\$repo/\$arch" >> /etc/pacman.conf

/bin/echo -e "\n" >> /etc/pacman.conf
/bin/echo -e "[liquorix]" >> /etc/pacman.conf
/bin/echo -e "Server = https://liquorix.net/archlinux/\$repo/\$arch" >> /etc/pacman.conf

pacman -Syu
pacman -S archlinux-keyring
