#!/bin/bash

useradd -m sadereksatia
usermod -aG wheel sadereksatia
usermod -aG libvirt sadereksatia

#printf "\e[1;32mMasukan Kata Sandi USER\e[0m\n"
/bin/echo -e "\e[1;32mMasukan Kata Sandi USER Dalam 5..4..3..2..1..\e[0m"
sleep 5
passwd sadereksatia

/bin/echo -e "\e[1;32mHarap Ubah Autentikasi USER Dengan Grup WHEEL Dalam 5..4..3..2..1..\e[0m"
sleep 5
nano /etc/sudoers
# Ganti menggunakan whell >> echo "sadereksatia ALL=(ALL) ALL" >> /etc/sudoers.d/sadereksatia
printf "\e[1;32mDone! Type exit, umount -a and reboot.\e[0m"
