#!/bin/bash

/bin/echo -e "[mesa-git]" >> /etc/pacman.conf
/bin/echo -e "Server = https://pkgbuild.com/~lcarlier/\$repo/\$arch" >> /etc/pacman.conf

/bin/echo -e "\n" >> /etc/pacman.conf
/bin/echo -e "[liquorix]" >> /etc/pacman.conf
/bin/echo -e "Server = https://liquorix.net/archlinux/\$repo/\$arch" >> /etc/pacman.conf

/bin/echo -e "\e[1;32mSaya Sarankan Aktifkan Repository Multilib Dari Sini\e[0m"
sleep 3
nano /etc/pacman.conf

cat /etc/pacman.conf

pacman -Syu
pacman -S archlinux-keyring
pacman -S linux-lqx linux-lqx-headers

/bin/echo -e "\e[1;32mInstall Juga Kernel CachyOS Dari Partisi USER\e[0m"
/bin/echo -e "\e[1;32m >> linux-cachyos linux-cachyos-headers linux-cachyos-bore linux-cachyos-bore-headers\e[0m"
