#!/bin/bash

systemctl enable NetworkManager
systemctl enable bluetooth
systemctl enable fstrim.timer
# systemctl enable acpid
# systemctl enable cups.service
# systemctl enable sshd
# systemctl enable avahi-daemon
# systemctl enable tlp
# systemctl enable reflector.timer
# systemctl enable libvirtd
