#!/bin/bash

pacman -S lib32-mesa lib32-opencl-rusticl-mesa lib32-opencl-clover-mesa lib32-mesa-vdpau lib32-libva-mesa-driver lib32-libva-vdpau-driver lib32-amdvlk lib32-vkd3d lib32-vulkan-mesa-layers lib32-vulkan-radeon lib32-vulkan-swrast  mesa opencl-rusticl-mesa opencl-clover-mesa mesa-vdpau libva-mesa-driver libva-vdpau-driver amdvlk vkd3d vulkan-mesa-layers vulkan-radeon vulkan-swrast libva-utils vulkan-tools opengl-man-pages xf86-video-amdgpu xorg-xgamma

#pacman -S clang-git compiler-rt-git lib32-libdrm-git lib32-llvm-git lib32-llvm-libs-git lib32-mesa-git lib32-vulkan-mesa-layers-git lib32-vulkan-radeon-git libclc-git libdrm-git lldb-git lld-git llvm-git llvm-libs-git mesa-git opencl-mesa-git polly-git python-sphinx-automodapi rusticl-mesa-git spirv-llvm-translator-git vulkan-mesa-layers-git vulkan-radeon-git xf86-video-amdgpu-git
