#!/bin/bash

pacman -S mesa lib32-mesa xf86-video-amdgpu vulkan-radeon lib32-vulkan-radeon amdvlk lib32-amdvlk libva-mesa-driver lib32-libva-mesa-driver mesa-vdpau lib32-mesa-vdpau vulkan-mesa-layers lib32-vulkan-mesa-layers opengl-man-pages

#pacman -S clang-git compiler-rt-git lib32-libdrm-git lib32-llvm-git lib32-llvm-libs-git lib32-mesa-git lib32-vulkan-mesa-layers-git lib32-vulkan-radeon-git libclc-git libdrm-git lldb-git lld-git llvm-git llvm-libs-git mesa-git opencl-mesa-git polly-git python-sphinx-automodapi rusticl-mesa-git spirv-llvm-translator-git vulkan-mesa-layers-git vulkan-radeon-git xf86-video-amdgpu-git
