#!/bin/bash

sudo pacman -S jasper libwebp lib32-libwebp libavif libheif libjxl librsvg lib32-librsvg libid3tag lib32-libid3tag
sudo pacman -S flac lib32-flac wavpack lib32-wavpack libvorbis lib32-libvorbis lame libmad a52dec libmpcdec opencore-amr opus lib32-opus speex lib32-speex libvorbis lib32-libvorbis faac faad2 libfdk-aac fluidsynth lib32-fluidsynth
sudo pacman -S aom dav1d rav1e svt-av1 libde265 libdv libmpeg2 schroedinger libtheora libvpx x264 x265 xvidcore
sudo pacman -S ffmpeg gstreamer gst-libav gst-plugins-bad gst-plugins-base gst-plugins-good gst-plugins-ugly libde265 gst-plugin-pipewire gstreamer-vaapi gst-plugin-va libva-mesa-driver lib32-libva-mesa-driver mesa-vdpau lib32-mesa-vdpau
sudo pacman -S unzip unrar p7zip
sudo pacman -S bison flex valgrind byacc polly python-pefile
