#!/bin/bash

#============================================================
# INIT			INIT			INIT
#============================================================

SUMBER_ARCHINSTALL='source Pase/'

# source Pase
# SUMBER_ARCHINSTALL/0-catatan
SUMBER_ARCHINSTALL/1-arch-partition
SUMBER_ARCHINSTALL/2-arch-install
SUMBER_ARCHINSTALL/3-arch-gnome
