#!/bin/bash

sudo pacman -S gdm gnome gnome-extra gnome-tweaks
sudo pacman -S adapta-gtk-theme arc-gtk-theme arc-solid-gtk-theme arc-icon-theme breeze-gtk deepin-gtk-theme gnome-themes-extra materia-gtk-theme mate-themes
sudo pacman -S blender pragha mpv gimp obs-studio firefox chromium libreoffice keybase telegram-desktop
sudo pacman -S bash-completion git gvim neovim neovide
